apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: microservices
  labels:
    app: shipping-service
spec:
  selector:
    app: shipping-service
  ports:
    - protocol: TCP
      port: 8600
      targetPort: 8600
  type: ClusterIP