apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: proxy-client
  ports:
    - name: http
      port: 8705
      targetPort: 8705
