apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: gab27x/order-service:dev
          ports:
            - containerPort: 8300
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_APPLICATION_NAME
              value: "ORDER-SERVICE"
            - name: SERVER_PORT
              value: "8300"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/order-service"

            # Servicios externos
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin-service:9411"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"

            # Eureka - Variables correctas seg√∫n Cloud Config
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

          livenessProbe:
            httpGet:
              path: /order-service/actuator/health/liveness
              port: 8300
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /order-service/actuator/health/readiness
              port: 8300
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config
